modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "laoxiang"
version = "0.1.3"
displayName = "LaoXiang (老乡)"
authors = "xiaohunao"
description = '''
Shows player IP locations above player heads on NeoForge servers.
'''

[[dependencies.laoxiang]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.laoxiang]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[features.iplocationdisplay]
openGLVersion = "[0,)"
