package com.xiaohunao.iplocationdisplay.location;

import java.text.Normalizer;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

final class ChinaCityLocalizer {
    private static final Map<String, String> CITY_BY_REGION_AND_NAME = buildCityMap();

    private ChinaCityLocalizer() {
    }

    static Optional<String> localize(String regionCode, String cityName) {
        String key = regionCode.toUpperCase(Locale.ROOT) + ":" + normalizeCityName(cityName);
        return Optional.ofNullable(CITY_BY_REGION_AND_NAME.get(key));
    }

    private static String normalizeCityName(String value) {
        String normalized = Normalizer.normalize(value, Normalizer.Form.NFKD)
                .replaceAll("\\p{M}", "")
                .toLowerCase(Locale.ROOT)
                .replace('ü', 'u')
                .replace('v', 'u')
                .replaceAll("[^a-z0-9]", "");
        if (normalized.endsWith("city")) {
            normalized = normalized.substring(0, normalized.length() - 4);
        }
        return normalized;
    }

    private static Map<String, String> buildCityMap() {
        Map<String, String> cities = new HashMap<>();
        String data = """
                AH:anqing=安庆市
                AH:bengbu=蚌埠市
                AH:bozhou=亳州市
                AH:chizhou=池州市
                AH:chuzhou=滁州市
                AH:fuyang=阜阳市
                AH:hefei=合肥市
                AH:huaibei=淮北市
                AH:huainan=淮南市
                AH:huangshan=黄山市
                AH:luan=六安市
                AH:maanshan=马鞍山市
                AH:suzhou=宿州市
                AH:tongling=铜陵市
                AH:wuhu=芜湖市
                AH:xuancheng=宣城市
                BJ:beijing=北京市
                CQ:chongqing=重庆市
                FJ:fuzhou=福州市
                FJ:longyan=龙岩市
                FJ:nanping=南平市
                FJ:ningde=宁德市
                FJ:putian=莆田市
                FJ:quanzhou=泉州市
                FJ:sanming=三明市
                FJ:xiamen=厦门市
                FJ:zhangzhou=漳州市
                GD:chaozhou=潮州市
                GD:dongguan=东莞市
                GD:foshan=佛山市
                GD:guangzhou=广州市
                GD:heyuan=河源市
                GD:huizhou=惠州市
                GD:jiangmen=江门市
                GD:jieyang=揭阳市
                GD:maoming=茂名市
                GD:meizhou=梅州市
                GD:qingyuan=清远市
                GD:shantou=汕头市
                GD:shanwei=汕尾市
                GD:shaoguan=韶关市
                GD:shenzhen=深圳市
                GD:yangjiang=阳江市
                GD:yunfu=云浮市
                GD:zhanjiang=湛江市
                GD:zhaoqing=肇庆市
                GD:zhongshan=中山市
                GD:zhuhai=珠海市
                GS:baiyin=白银市
                GS:dingxi=定西市
                GS:gannan=甘南藏族自治州
                GS:jiayuguan=嘉峪关市
                GS:jinchang=金昌市
                GS:jiuquan=酒泉市
                GS:lanzhou=兰州市
                GS:linxia=临夏回族自治州
                GS:longnan=陇南市
                GS:pingliang=平凉市
                GS:qingyang=庆阳市
                GS:tianshui=天水市
                GS:wuwei=武威市
                GS:zhangye=张掖市
                GX:baise=百色市
                GX:beihai=北海市
                GX:chongzuo=崇左市
                GX:fangchenggang=防城港市
                GX:guigang=贵港市
                GX:guilin=桂林市
                GX:hechi=河池市
                GX:hezhou=贺州市
                GX:laibin=来宾市
                GX:liuzhou=柳州市
                GX:nanning=南宁市
                GX:qinzhou=钦州市
                GX:wuzhou=梧州市
                GX:yulin=玉林市
                GZ:anshun=安顺市
                GZ:bijie=毕节市
                GZ:guiyang=贵阳市
                GZ:liupanshui=六盘水市
                GZ:qiandongnan=黔东南苗族侗族自治州
                GZ:qiannan=黔南布依族苗族自治州
                GZ:qianxinan=黔西南布依族苗族自治州
                GZ:tongren=铜仁市
                GZ:zunyi=遵义市
                HA:anyang=安阳市
                HA:hebi=鹤壁市
                HA:jiaozuo=焦作市
                HA:kaifeng=开封市
                HA:luohe=漯河市
                HA:luoyang=洛阳市
                HA:nanyang=南阳市
                HA:pingdingshan=平顶山市
                HA:puyang=濮阳市
                HA:sanmenxia=三门峡市
                HA:shangqiu=商丘市
                HA:xinxiang=新乡市
                HA:xinyang=信阳市
                HA:xuchang=许昌市
                HA:zhengzhou=郑州市
                HA:zhoukou=周口市
                HA:zhumadian=驻马店市
                HB:enshi=恩施土家族苗族自治州
                HB:ezhou=鄂州市
                HB:huanggang=黄冈市
                HB:huangshi=黄石市
                HB:jingmen=荆门市
                HB:jingzhou=荆州市
                HB:shiyan=十堰市
                HB:suizhou=随州市
                HB:wuhan=武汉市
                HB:xiangyang=襄阳市
                HB:xianning=咸宁市
                HB:xiaogan=孝感市
                HB:yichang=宜昌市
                HE:baoding=保定市
                HE:cangzhou=沧州市
                HE:chengde=承德市
                HE:handan=邯郸市
                HE:hengshui=衡水市
                HE:langfang=廊坊市
                HE:qinhuangdao=秦皇岛市
                HE:shijiazhuang=石家庄市
                HE:tangshan=唐山市
                HE:xingtai=邢台市
                HE:zhangjiakou=张家口市
                HI:danzhou=儋州市
                HI:haikou=海口市
                HI:sansha=三沙市
                HI:sanya=三亚市
                HL:daqing=大庆市
                HL:daxinganling=大兴安岭地区
                HL:haerbin=哈尔滨市
                HL:harbin=哈尔滨市
                HL:hegang=鹤岗市
                HL:heihe=黑河市
                HL:jiamusi=佳木斯市
                HL:jixi=鸡西市
                HL:mudanjiang=牡丹江市
                HL:qiqihaer=齐齐哈尔市
                HL:qiqihar=齐齐哈尔市
                HL:qitaihe=七台河市
                HL:shuangyashan=双鸭山市
                HL:suihua=绥化市
                HL:yichun=伊春市
                HN:changde=常德市
                HN:changsha=长沙市
                HN:chenzhou=郴州市
                HN:hengyang=衡阳市
                HN:huaihua=怀化市
                HN:loudi=娄底市
                HN:shaoyang=邵阳市
                HN:xiangtan=湘潭市
                HN:xiangxi=湘西土家族苗族自治州
                HN:yiyang=益阳市
                HN:yongzhou=永州市
                HN:yueyang=岳阳市
                HN:zhangjiajie=张家界市
                HN:zhuzhou=株洲市
                JL:baicheng=白城市
                JL:baishan=白山市
                JL:changchun=长春市
                JL:jilin=吉林市
                JL:liaoyuan=辽源市
                JL:siping=四平市
                JL:songyuan=松原市
                JL:tonghua=通化市
                JL:yanbian=延边朝鲜族自治州
                JS:changzhou=常州市
                JS:huaian=淮安市
                JS:lianyungang=连云港市
                JS:nanjing=南京市
                JS:nantong=南通市
                JS:suqian=宿迁市
                JS:suzhou=苏州市
                JS:taizhou=泰州市
                JS:wuxi=无锡市
                JS:xuzhou=徐州市
                JS:yancheng=盐城市
                JS:yangzhou=扬州市
                JS:zhenjiang=镇江市
                JX:fuzhou=抚州市
                JX:ganzhou=赣州市
                JX:jian=吉安市
                JX:jingdezhen=景德镇市
                JX:jiujiang=九江市
                JX:nanchang=南昌市
                JX:pingxiang=萍乡市
                JX:shangrao=上饶市
                JX:xinyu=新余市
                JX:yichun=宜春市
                JX:yingtan=鹰潭市
                LN:anshan=鞍山市
                LN:benxi=本溪市
                LN:chaoyang=朝阳市
                LN:dalian=大连市
                LN:dandong=丹东市
                LN:fushun=抚顺市
                LN:fuxin=阜新市
                LN:huludao=葫芦岛市
                LN:jinzhou=锦州市
                LN:liaoyang=辽阳市
                LN:panjin=盘锦市
                LN:shenyang=沈阳市
                LN:tieling=铁岭市
                LN:yingkou=营口市
                NM:alashan=阿拉善盟
                NM:baotou=包头市
                NM:bayannaoer=巴彦淖尔市
                NM:bayannur=巴彦淖尔市
                NM:chifeng=赤峰市
                NM:eerduosi=鄂尔多斯市
                NM:hohhot=呼和浩特市
                NM:huhehaote=呼和浩特市
                NM:hulunbeier=呼伦贝尔市
                NM:hulunbuir=呼伦贝尔市
                NM:ordos=鄂尔多斯市
                NM:tongliao=通辽市
                NM:wuhai=乌海市
                NM:wulanchabu=乌兰察布市
                NM:xilingol=锡林郭勒盟
                NM:xilinguole=锡林郭勒盟
                NM:xingan=兴安盟
                NX:guyuan=固原市
                NX:shizuishan=石嘴山市
                NX:wuzhong=吴忠市
                NX:yinchuan=银川市
                NX:zhongwei=中卫市
                QH:guoluo=果洛藏族自治州
                QH:haibei=海北藏族自治州
                QH:haidong=海东市
                QH:hainan=海南藏族自治州
                QH:haixi=海西蒙古族藏族自治州
                QH:huangnan=黄南藏族自治州
                QH:xining=西宁市
                QH:yushu=玉树藏族自治州
                SC:aba=阿坝藏族羌族自治州
                SC:bazhong=巴中市
                SC:chengdu=成都市
                SC:dazhou=达州市
                SC:deyang=德阳市
                SC:ganzi=甘孜藏族自治州
                SC:garze=甘孜藏族自治州
                SC:guangan=广安市
                SC:guangyuan=广元市
                SC:leshan=乐山市
                SC:liangshan=凉山彝族自治州
                SC:luzhou=泸州市
                SC:meishan=眉山市
                SC:mianyang=绵阳市
                SC:nanchong=南充市
                SC:neijiang=内江市
                SC:ngawa=阿坝藏族羌族自治州
                SC:panzhihua=攀枝花市
                SC:suining=遂宁市
                SC:yaan=雅安市
                SC:yibin=宜宾市
                SC:zigong=自贡市
                SC:ziyang=资阳市
                SD:binzhou=滨州市
                SD:dezhou=德州市
                SD:dongying=东营市
                SD:heze=菏泽市
                SD:jinan=济南市
                SD:jining=济宁市
                SD:liaocheng=聊城市
                SD:linyi=临沂市
                SD:qingdao=青岛市
                SD:rizhao=日照市
                SD:taian=泰安市
                SD:weifang=潍坊市
                SD:weihai=威海市
                SD:yantai=烟台市
                SD:zaozhuang=枣庄市
                SD:zibo=淄博市
                SH:shanghai=上海市
                SN:ankang=安康市
                SN:baoji=宝鸡市
                SN:hanzhong=汉中市
                SN:shangluo=商洛市
                SN:tongchuan=铜川市
                SN:weinan=渭南市
                SN:xian=西安市
                SN:xianyang=咸阳市
                SN:yanan=延安市
                SN:yulin=榆林市
                SX:changzhi=长治市
                SX:datong=大同市
                SX:jincheng=晋城市
                SX:jinzhong=晋中市
                SX:linfen=临汾市
                SX:luliang=吕梁市
                SX:shuozhou=朔州市
                SX:taiyuan=太原市
                SX:xinzhou=忻州市
                SX:yangquan=阳泉市
                SX:yuncheng=运城市
                TJ:tianjin=天津市
                XJ:akesu=阿克苏地区
                XJ:aksu=阿克苏地区
                XJ:aletai=阿勒泰地区
                XJ:altay=阿勒泰地区
                XJ:bayingolin=巴音郭楞蒙古自治州
                XJ:bortala=博尔塔拉蒙古自治州
                XJ:boertala=博尔塔拉蒙古自治州
                XJ:changji=昌吉回族自治州
                XJ:hami=哈密市
                XJ:hetian=和田地区
                XJ:hotan=和田地区
                XJ:ili=伊犁哈萨克自治州
                XJ:karamay=克拉玛依市
                XJ:kashen=喀什地区
                XJ:kashgar=喀什地区
                XJ:kelamayi=克拉玛依市
                XJ:kizilsu=克孜勒苏柯尔克孜自治州
                XJ:tacheng=塔城地区
                XJ:tulufan=吐鲁番市
                XJ:turpan=吐鲁番市
                XJ:urumqi=乌鲁木齐市
                XJ:wulumuqi=乌鲁木齐市
                XZ:ali=阿里地区
                XZ:changdou=昌都市
                XZ:lasa=拉萨市
                XZ:lhasa=拉萨市
                XZ:linzhi=林芝市
                XZ:nagqu=那曲市
                XZ:ngari=阿里地区
                XZ:nyingchi=林芝市
                XZ:naqu=那曲市
                XZ:rikaze=日喀则市
                XZ:shannan=山南市
                XZ:shigatse=日喀则市
                YN:baoshan=保山市
                YN:chuxiong=楚雄彝族自治州
                YN:dali=大理白族自治州
                YN:dalibaizu=大理白族自治州
                YN:dehong=德宏傣族景颇族自治州
                YN:diqing=迪庆藏族自治州
                YN:honghe=红河哈尼族彝族自治州
                YN:kunming=昆明市
                YN:lijiang=丽江市
                YN:lincang=临沧市
                YN:nujiang=怒江傈僳族自治州
                YN:puer=普洱市
                YN:qujing=曲靖市
                YN:wenshan=文山壮族苗族自治州
                YN:xishuangbanna=西双版纳傣族自治州
                YN:yuxi=玉溪市
                YN:zhaotong=昭通市
                ZJ:hangzhou=杭州市
                ZJ:huzhou=湖州市
                ZJ:jiaxing=嘉兴市
                ZJ:jinhua=金华市
                ZJ:lishui=丽水市
                ZJ:ningbo=宁波市
                ZJ:quzhou=衢州市
                ZJ:shaoxing=绍兴市
                ZJ:taizhou=台州市
                ZJ:wenzhou=温州市
                ZJ:zhoushan=舟山市
                """;

        for (String line : data.split("\\R")) {
            String trimmed = line.trim();
            if (!trimmed.isEmpty()) {
                int separator = trimmed.indexOf('=');
                cities.put(trimmed.substring(0, separator), trimmed.substring(separator + 1));
            }
        }
        return Map.copyOf(cities);
    }
}
